# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Skeletal"
license = "MIT"
licenselink = "https://github.com/rvbhute/skeletal/blob/master/LICENSE.md"
description = "Skeletal theme for Hugo based on Skeleton Framework"
homepage = "https://github.com/rvbhute/skeletal"
tags = ["skeleton", "single column"]
features = ["", ""]
min_version = 0.16

[author]
  name = "Rohit Bhute"
  homepage = ""
